version: '3'

services:
    web:
        build: .
        restart: always
        ports:
            - '8009:8000'
        env_file:
            - .env
        depends_on:
            - postgres
            - redis
    postgres:
        image: postgres:latest
        restart: always
        env_file:
            - .env
        volumes:
            - postgres_data:/var/lib/postgresql/data
            - ./postgres-init:/docker-entrypoint-initdb.d
    pgadmin:
        image: dpage/pgadmin4
        container_name: pgadmin4_container
        restart: always
        ports:
            - '8888:80'
        environment:
            PGADMIN_DEFAULT_EMAIL: nekgo2009@gmail.com
            PGADMIN_DEFAULT_PASSWORD: qwerty
        volumes:
            - pgadmin-data:/var/lib/pgadmin
    redis:
        image: redis:alpine
        restart: always

volumes:
    postgres_data:
    pgadmin-data:
