version: '3'

services:
    web:
        build: .
        restart: always
        ports:
            - '8009:8000'
        env_file:
            - .env
        depends_on:
            - postgres
            - redis
        volumes:
            - ./data:/app/data # Для хранения данных

    postgres:
        image: postgres:latest
        restart: always
        env_file:
            - .env
        ports:
            - '5434:5434'
        volumes:
            - postgres_data:/var/lib/postgresql/data
            - ./postgres-init:/docker-entrypoint-initdb.d

    redis:
        image: redis:alpine
        restart: always
        ports:
            - '6378:6379'

volumes:
    postgres_data:
